---
- name: install nginx
  yum: name=nginx state=installed 

- name: site config
  template: src=site.conf.j2 dest=/etc/nginx/conf.d/site.conf

- name: ensure nginx is running
  service: name=nginx state=started
