---
- name: install php and fpm
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-cli
    - php-curl
    - php-fpm
    - php-gd
    - php-json
    - php-mbstring
    - php-mcrypt
    - php-pdo
    - php-mysql
    - php-xml
